
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestWebserviceImp", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestWebserviceImp {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://webservice/", className = "webservice.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://webservice/", className = "webservice.GetNameResponse")
    @Action(input = "http://webservice/TestWebserviceImp/getNameRequest", output = "http://webservice/TestWebserviceImp/getNameResponse")
    public String getName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://webservice/", className = "webservice.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://webservice/", className = "webservice.GetAllResponse")
    @Action(input = "http://webservice/TestWebserviceImp/getAllRequest", output = "http://webservice/TestWebserviceImp/getAllResponse")
    public String getAll();

}
