
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestWebserviceImpService", targetNamespace = "http://webservice/", wsdlLocation = "http://localhost:8090/service?wsdl")
public class TestWebserviceImpService
    extends Service
{

    private final static URL TESTWEBSERVICEIMPSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTWEBSERVICEIMPSERVICE_EXCEPTION;
    private final static QName TESTWEBSERVICEIMPSERVICE_QNAME = new QName("http://webservice/", "TestWebserviceImpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTWEBSERVICEIMPSERVICE_WSDL_LOCATION = url;
        TESTWEBSERVICEIMPSERVICE_EXCEPTION = e;
    }

    public TestWebserviceImpService() {
        super(__getWsdlLocation(), TESTWEBSERVICEIMPSERVICE_QNAME);
    }

    public TestWebserviceImpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTWEBSERVICEIMPSERVICE_QNAME, features);
    }

    public TestWebserviceImpService(URL wsdlLocation) {
        super(wsdlLocation, TESTWEBSERVICEIMPSERVICE_QNAME);
    }

    public TestWebserviceImpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTWEBSERVICEIMPSERVICE_QNAME, features);
    }

    public TestWebserviceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWebserviceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestWebserviceImp
     */
    @WebEndpoint(name = "TestWebserviceImpPort")
    public TestWebserviceImp getTestWebserviceImpPort() {
        return super.getPort(new QName("http://webservice/", "TestWebserviceImpPort"), TestWebserviceImp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebserviceImp
     */
    @WebEndpoint(name = "TestWebserviceImpPort")
    public TestWebserviceImp getTestWebserviceImpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "TestWebserviceImpPort"), TestWebserviceImp.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTWEBSERVICEIMPSERVICE_EXCEPTION!= null) {
            throw TESTWEBSERVICEIMPSERVICE_EXCEPTION;
        }
        return TESTWEBSERVICEIMPSERVICE_WSDL_LOCATION;
    }

}
